name: Run Moyoplan Daily (test)

on:
  schedule:
    - cron: '0 22 * * *'  # 매일 오후 10시 (한국 시간 오전 7시)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_260303.txt

      - name: Run script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python 알뜰폰닷컴_프로모션조사_구문.py
